# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_notifications', '0004_auto_20170124_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonesent',
            old_name='twilio_error_code',
            new_name='error_code',
        ),
        migrations.RenameField(
            model_name='phonesent',
            old_name='twilio_error_message',
            new_name='error_message',
        ),
        migrations.AlterField(
            model_name='phonereceiver',
            name='service_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
