# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 12:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('universal_notifications', '0007_auto_20170323_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
